### PR TITLE
merge the solutions into the main branch

### PR DESCRIPTION
**Pull request by lostmygithubaccount**

### CODE REVIEW

**Comment by lostmygithubaccount** [comment]
very confused by the diff...will need to come back to this

**Comment by lostmygithubaccount** [comment]
oh

**Comment by wasilaq** [comment]
FYI I think we want to keep the solutions branch separate so new folks can come in and play with these challenges. The workshop code should be available indefinitely (both the problems and solutions)

**Comment by lostmygithubaccount** [comment]
@wasilaq sounds good, I'll close this PR then

**Pull request closed without merging**
